### ISSUE TITLE
404 ERROR for the dataset link

### ISSUE THREAD

**Issue by DavidJiang9** [Wendy-Xiao/redundancy_reduction_longdoc#1]
Hi,thx for sharing. I have found that the preprocessed data link is invalid. Can you fix it? 
It seems that the data here has different structure from the data in your "Extsumm_local_global_context" repo.

**Comment by Wendy-Xiao** [comment]
Hi, thanks for your interest in the work! I have updated the links to the datasets in the readme, now you should be able to get them.

**Comment by DavidJiang9** [comment]
thanks a lot. now it's available for me.
